import { useEffect, useState } from 'react';
import { FiBarChart2, FiRefreshCw, FiShield, FiUsers } from 'react-icons/fi';
import AppShell from '../components/AppShell';
import LoadingSpinner from '../components/LoadingSpinner';
import { adminService } from '../services/adminService';
import { getErrorMessage } from '../services/api';

const humanDate = (date) => date ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date)) : '—';
export default function AdminDashboard() {
  const [state, setState] = useState({ loading: true, users: [], stats: null, error: '' }); const [updating, setUpdating] = useState('');
  const load = async () => { setState((current) => ({ ...current, loading: true, error: '' })); try { const [stats, userResponse] = await Promise.all([adminService.stats(), adminService.users()]); setState({ loading: false, stats, users: userResponse.data || [], error: '' }); } catch (err) { setState({ loading: false, users: [], stats: null, error: getErrorMessage(err, 'Admin data could not be loaded.') }); } };
  useEffect(() => { load(); }, []);
  const updateTier = async (id, tier) => { setUpdating(id); try { await adminService.updateTier(id, tier); setState((current) => ({ ...current, users: current.users.map((user) => user._id === id ? { ...user, userTier: tier } : user) })); } catch (err) { setState((current) => ({ ...current, error: getErrorMessage(err, 'The user tier could not be updated.') })); } finally { setUpdating(''); } };
  return <AppShell eyebrow="RESTRICTED AREA" title="Administration" action={<button className="button button-outline" onClick={load}><FiRefreshCw /> Refresh</button>}>{state.loading ? <LoadingSpinner label="Loading administration data" /> : <>{state.error && <p className="notice notice-error">{state.error}</p>}<section className="admin-stats"><article><span><FiUsers /></span><p>Total active users</p><strong>{state.stats?.totalUsers ?? '—'}</strong></article><article><span><FiShield /></span><p>Premium users</p><strong>{state.stats?.premiumUsers ?? '—'}</strong></article><article><span><FiBarChart2 /></span><p>Recorded revenue</p><strong>₹{Number(state.stats?.totalRevenue || 0).toLocaleString('en-IN')}</strong></article></section><section className="admin-table-card"><header><div><p className="eyebrow">USERS</p><h2>Account access</h2></div><span>{state.users.length} users</span></header><div className="admin-table"><div className="admin-table-head"><span>User</span><span>Joined</span><span>Tier</span><span>Access</span></div>{state.users.map((user) => <div key={user._id} className="admin-user-row"><span className="admin-user"><i>{`${user.firstName?.[0] || ''}${user.lastName?.[0] || ''}`}</i><span><strong>{user.firstName} {user.lastName}</strong><small>{user.email}</small></span></span><span>{humanDate(user.createdAt)}</span><span><b className={`tier-badge tier-${user.userTier || user.subscriptionStatus || 'free'}`}>{user.userTier || user.subscriptionStatus || 'free'}</b></span><span><select aria-label={`Change tier for ${user.email}`} value={user.userTier || 'free'} disabled={updating === user._id} onChange={(event) => updateTier(user._id, event.target.value)}><option value="free">Free</option><option value="basic">Basic</option><option value="premium">Premium</option><option value="enterprise">Enterprise</option></select></span></div>)}</div></section></>}</AppShell>;
}
