import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { FiChevronLeft, FiEdit2, FiFileText, FiMessageCircle, FiMoreHorizontal, FiPlus, FiSearch, FiTrash2, FiX } from 'react-icons/fi';
import AppShell from '../components/AppShell';
import ChatInput from '../components/ChatInput';
import ChatMessage from '../components/ChatMessage';
import LoadingSpinner from '../components/LoadingSpinner';
import { chatService } from '../services/chatService';
import { documentService } from '../services/documentService';
import { getErrorMessage } from '../services/api';

const newSlug = () => globalThis.crypto?.randomUUID?.() || `chat-${Date.now()}`;
const timeLabel = (value) => value ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(value)) : '';
export default function ChatPage() {
  const [params, setParams] = useSearchParams(); const sessionParam = params.get('session'); const initialSlug = sessionParam || 'default'; const [activeSlug, setActiveSlug] = useState(initialSlug); const [sessions, setSessions] = useState([]); const [messages, setMessages] = useState([]); const [attachment, setAttachment] = useState(null); const [loadingHistory, setLoadingHistory] = useState(true); const [sending, setSending] = useState(false); const [panelOpen, setPanelOpen] = useState(false); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [renaming, setRenaming] = useState(null); const [renameValue, setRenameValue] = useState(''); const endRef = useRef(null);
  const loadSessions = useCallback(async () => { try { const result = await chatService.getSessions(); setSessions(Array.isArray(result) ? result.filter((item) => item.type === 'chat' || !item.type) : []); } catch (err) { setError(getErrorMessage(err, 'We could not load your conversations.')); } }, []);
  const loadHistory = useCallback(async (slug) => { setLoadingHistory(true); setError(''); try { const result = await chatService.getHistory(slug); setMessages(result.messages || []); } catch (err) { setMessages([]); setError(getErrorMessage(err, 'We could not load this conversation.')); } finally { setLoadingHistory(false); } }, []);
  useEffect(() => { loadSessions(); }, [loadSessions]);
  useEffect(() => { loadHistory(activeSlug); if (sessionParam !== activeSlug) setParams(activeSlug === 'default' ? {} : { session: activeSlug }, { replace: true }); }, [activeSlug, loadHistory, sessionParam, setParams]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, sending]);
  const switchSession = (slug) => { setActiveSlug(slug); setAttachment(null); setPanelOpen(false); };
  const makeNew = () => switchSession(newSlug());
  const send = async (content) => { setError(''); setSending(true); const optimistic = { role: 'user', content, timestamp: new Date().toISOString(), file: attachment ? { fileName: attachment.name } : undefined }; setMessages((current) => [...current, optimistic]); try { let fileId; if (attachment) { const upload = await documentService.upload(attachment); fileId = upload.file?._id; if (!fileId) throw new Error('The document upload did not return a file ID.'); } const response = await chatService.sendMessage(activeSlug, { message: content, fileId, language: 'en' }); setMessages((current) => [...current, { role: 'assistant', content: response.response || 'I could not generate a response for that request.', timestamp: new Date().toISOString(), file: response.file, document: response.document }]); setAttachment(null); await loadSessions(); return true; } catch (err) { setMessages((current) => current.slice(0, -1)); setError(getErrorMessage(err, 'Your message was not sent.')); return false; } finally { setSending(false); } };
  const removeSession = async (event, slug) => { event.stopPropagation(); if (!window.confirm('Delete this conversation? This cannot be undone.')) return; try { await chatService.deleteSession(slug); setSessions((items) => items.filter((item) => item.slug !== slug)); if (slug === activeSlug) makeNew(); } catch (err) { setError(getErrorMessage(err, 'This conversation could not be deleted.')); } };
  const saveRename = async (event, slug) => { event.preventDefault(); const title = renameValue.trim(); if (!title) return; try { await chatService.renameSession(slug, title); setSessions((items) => items.map((item) => item.slug === slug ? { ...item, title } : item)); setRenaming(null); } catch (err) { setError(getErrorMessage(err, 'The conversation name could not be updated.')); } };
  const visibleSessions = sessions.filter((session) => `${session.title} ${session.preview}`.toLowerCase().includes(query.toLowerCase()));
  const isNew = !sessions.some((session) => session.slug === activeSlug);
  return <AppShell wide title="Legal assistant" eyebrow="AI-ASSISTED LEGAL RESEARCH"><div className="chat-layout"><aside className={`conversation-panel ${panelOpen ? 'is-open' : ''}`}><div className="conversation-panel-head"><button className="button button-dark full-width" onClick={makeNew}><FiPlus /> New conversation</button><button className="conversation-close" onClick={() => setPanelOpen(false)}><FiX /></button></div><label className="conversation-search"><FiSearch /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search conversations" /></label><div className="conversation-list">{visibleSessions.length ? visibleSessions.map((session) => <div key={session.slug} className={`conversation-item ${session.slug === activeSlug ? 'active' : ''}`} onClick={() => switchSession(session.slug)} role="button" tabIndex="0" onKeyDown={(event) => event.key === 'Enter' && switchSession(session.slug)}>{renaming === session.slug ? <form onSubmit={(event) => saveRename(event, session.slug)}><input autoFocus value={renameValue} onChange={(event) => setRenameValue(event.target.value)} onBlur={() => setRenaming(null)} /></form> : <><FiMessageCircle /><span><strong>{session.title || 'Conversation'}</strong><small>{timeLabel(session.updatedAt)}</small></span><div className="conversation-actions"><button aria-label="Rename conversation" onClick={(event) => { event.stopPropagation(); setRenaming(session.slug); setRenameValue(session.title || 'Conversation'); }}><FiEdit2 /></button><button aria-label="Delete conversation" onClick={(event) => removeSession(event, session.slug)}><FiTrash2 /></button></div></>}</div>) : <div className="conversation-empty">{query ? 'No conversations match that search.' : 'Your saved conversations will appear here.'}</div>}</div><Link className="panel-doc-link" to="/documents"><FiFileText /> Your documents <FiChevronLeft /></Link></aside>{panelOpen && <button className="panel-backdrop" aria-label="Close conversation menu" onClick={() => setPanelOpen(false)} />}
    <section className="chat-stage"><header className="chat-stage-head"><button className="small-icon-button chat-mobile-toggle" onClick={() => setPanelOpen(true)}><FiMoreHorizontal /></button><div><p className="eyebrow">{isNew ? 'NEW CONVERSATION' : 'SAVED CONVERSATION'}</p><h2>{isNew ? 'How can I help today?' : sessions.find((session) => session.slug === activeSlug)?.title || 'Conversation'}</h2></div><span className="online-status"><i /> Assistant ready</span></header>{error && <div className="notice notice-error"><span>{error}</span><button onClick={() => setError('')}><FiX /></button></div>}<div className="chat-scroll">{loadingHistory ? <LoadingSpinner label="Loading conversation" /> : messages.length ? <div className="messages">{messages.map((message, index) => <ChatMessage key={`${message.timestamp || index}-${message.role}`} message={message} />)}{sending && <div className="typing-indicator"><span /><span /><span /> Dastavez AI is thinking</div>}<div ref={endRef} /></div> : <div className="chat-empty"><span className="chat-empty-mark"><FiMessageCircle /></span><p className="eyebrow">A PRIVATE STARTING POINT</p><h3>Ask about a legal matter.</h3><p>Describe a situation, upload a supporting document, or ask for help preparing a legal draft.</p><div><button onClick={() => send('Help me understand the key points I should gather before consulting a lawyer.')}>What details should I gather?</button><button onClick={() => send('What should I look for when reviewing a legal document?')}>How do I review a document?</button></div></div>}</div><ChatInput onSend={send} isSending={sending} attachment={attachment} onAttachment={setAttachment} onClearAttachment={() => setAttachment(null)} /></section></div></AppShell>;
}
