import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { FiArrowRight, FiClock, FiFileText, FiMessageCircle, FiPlus, FiUploadCloud } from 'react-icons/fi';
import AppShell from '../components/AppShell';
import LoadingSpinner from '../components/LoadingSpinner';
import { useAuth } from '../context/AuthContext';
import { chatService } from '../services/chatService';
import { documentService } from '../services/documentService';
import { subscriptionService } from '../services/subscriptionService';

const dateLabel = (value) => value ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(value)) : 'Recently';
export default function Dashboard() {
  const { user } = useAuth(); const [state, setState] = useState({ loading: true, sessions: [], files: [], subscription: null, error: '' });
  useEffect(() => { let alive = true; Promise.allSettled([chatService.getSessions(), documentService.list(), subscriptionService.mine()]).then(([sessions, files, subscription]) => { if (!alive) return; setState({ loading: false, sessions: sessions.status === 'fulfilled' ? sessions.value : [], files: files.status === 'fulfilled' ? files.value : [], subscription: subscription.status === 'fulfilled' ? subscription.value.subscription : null, error: sessions.status === 'rejected' && files.status === 'rejected' ? 'We could not load your workspace data. Check that the server is running.' : '' }); }); return () => { alive = false; }; }, []);
  const firstName = user?.firstName || 'there';
  return <AppShell eyebrow="YOUR WORKSPACE" title={`Good to see you, ${firstName}.`} action={<Link className="button button-dark" to="/chat"><FiPlus /> New conversation</Link>}>{state.loading ? <LoadingSpinner label="Loading your workspace" /> : <><section className="welcome-panel"><div><p>LEGAL INTELLIGENCE WORKSPACE</p><h2>What would you like to work through today?</h2><span>Start an AI-assisted legal conversation or bring in a document for review.</span></div><div className="welcome-actions"><Link to="/chat" className="quick-action"><FiMessageCircle /><span><strong>Ask the assistant</strong><small>Explore a legal question</small></span><FiArrowRight /></Link><Link to="/documents" className="quick-action"><FiUploadCloud /><span><strong>Review a document</strong><small>Upload and analyze a file</small></span><FiArrowRight /></Link></div></section>{state.error && <p className="notice notice-error">{state.error}</p>}<section className="dashboard-grid"><div className="dashboard-card recent-card"><div className="card-heading"><div><p className="eyebrow">RECENT</p><h2>Conversations</h2></div><Link to="/chat">View all <FiArrowRight /></Link></div>{state.sessions.length ? <div className="recent-list">{state.sessions.slice(0, 4).map((session) => <Link className="recent-row" to={`/chat?session=${encodeURIComponent(session.slug)}`} key={session.slug}><span className="row-icon"><FiMessageCircle /></span><span><strong>{session.title || 'Conversation'}</strong><small>{session.preview || 'Continue your legal AI conversation'}</small></span><time><FiClock /> {dateLabel(session.updatedAt)}</time></Link>)}</div> : <div className="empty-inline"><FiMessageCircle /><p>No saved conversations yet.</p><Link to="/chat">Start your first one <FiArrowRight /></Link></div>}</div><div className="dashboard-card documents-card"><div className="card-heading"><div><p className="eyebrow">YOUR FILES</p><h2>Documents</h2></div><Link to="/documents">Manage <FiArrowRight /></Link></div>{state.files.length ? <div className="doc-mini-list">{state.files.slice(0, 4).map((file) => <Link to="/documents" className="doc-mini" key={file._id}><FiFileText /><span><strong>{file.fileName}</strong><small>Added {dateLabel(file.createdAt)}</small></span></Link>)}</div> : <div className="empty-inline"><FiFileText /><p>Your uploaded documents will appear here.</p><Link to="/documents">Upload a document <FiArrowRight /></Link></div>}</div></section><section className="access-strip"><div><p className="eyebrow">CURRENT ACCESS</p><h2>{state.subscription?.tier || user?.subscriptionStatus || 'Free'} plan</h2><p>{state.subscription?.status === 'active' ? 'Your subscription is active.' : 'Your account is ready to use.'}</p></div><Link className="button button-outline" to="/subscription">View plan details <FiArrowRight /></Link></section></>}</AppShell>;
}
