import { useEffect, useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { FiDownload, FiFileText, FiMoreHorizontal, FiSearch, FiTrash2, FiUploadCloud, FiX } from 'react-icons/fi';
import AppShell from '../components/AppShell';
import LoadingSpinner from '../components/LoadingSpinner';
import { documentService } from '../services/documentService';
import { getErrorMessage } from '../services/api';

const sizeLabel = (size) => size ? `${(size / (1024 * 1024)).toFixed(size > 1024 * 1024 ? 1 : 2)} MB` : '—';
const dateLabel = (date) => date ? new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(date)) : '—';
export default function Documents() {
  const input = useRef(null); const [files, setFiles] = useState([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [query, setQuery] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [analysis, setAnalysis] = useState(null); const [analyzing, setAnalyzing] = useState(null);
  const load = async () => { setLoading(true); try { setFiles(await documentService.list()); } catch (err) { setError(getErrorMessage(err, 'We could not load your documents.')); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const upload = async (file) => { if (!file) return; setError(''); setNotice(''); setUploading(true); try { const result = await documentService.upload(file); setFiles((items) => [result.file, ...items]); setNotice(`${file.name} was added to your documents.`); } catch (err) { setError(getErrorMessage(err, 'This document could not be uploaded.')); } finally { setUploading(false); if (input.current) input.current.value = ''; } };
  const analyze = async (file) => { setAnalyzing(file._id); setError(''); try { setAnalysis({ fileName: file.fileName, ...(await documentService.analyze(file._id, { question: 'Provide a clear legal summary, key obligations, important dates, risks, and practical follow-up questions.', language: 'en' })) }); } catch (err) { setError(getErrorMessage(err, 'This document could not be analyzed.')); } finally { setAnalyzing(null); } };
  const download = async (file) => { try { const blob = await documentService.download(file._id); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.fileName || 'document'; anchor.click(); URL.revokeObjectURL(url); } catch (err) { setError(getErrorMessage(err, 'This file could not be downloaded.')); } };
  const remove = async (file) => { if (!window.confirm(`Delete ${file.fileName}?`)) return; try { await documentService.delete(file._id); setFiles((items) => items.filter((item) => item._id !== file._id)); } catch (err) { setError(getErrorMessage(err, 'This file could not be deleted.')); } };
  const filtered = files.filter((file) => file.fileName?.toLowerCase().includes(query.toLowerCase()));
  return <AppShell eyebrow="DOCUMENT WORKSPACE" title="Your documents" action={<><input ref={input} hidden type="file" accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg" onChange={(event) => upload(event.target.files?.[0])} /><button className="button button-dark" onClick={() => input.current?.click()} disabled={uploading}><FiUploadCloud /> {uploading ? 'Uploading…' : 'Upload document'}</button></>}><section className="document-toolbar"><div><p>Store supporting files here, then request an AI-assisted analysis when you are ready.</p></div><label className="search-box"><FiSearch /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search documents" /></label></section>{notice && <p className="notice notice-success">{notice}</p>}{error && <div className="notice notice-error"><span>{error}</span><button onClick={() => setError('')}><FiX /></button></div>}{loading ? <LoadingSpinner label="Loading documents" /> : filtered.length ? <section className="document-table"><div className="document-table-head"><span>Document</span><span>Added</span><span>Size</span><span>Actions</span></div>{filtered.map((file) => <article key={file._id} className="document-row"><div className="document-name"><span className="file-icon"><FiFileText /></span><span><strong>{file.fileName}</strong><small>{file.fileType?.split('/').pop()?.toUpperCase() || 'FILE'}</small></span></div><span>{dateLabel(file.createdAt)}</span><span>{sizeLabel(file.fileSize)}</span><div className="document-actions"><button title="Analyze with AI" onClick={() => analyze(file)} disabled={analyzing === file._id}>{analyzing === file._id ? <LoadingSpinner /> : <FiMoreHorizontal />}</button><button title="Download" onClick={() => download(file)}><FiDownload /></button><button title="Delete" onClick={() => remove(file)}><FiTrash2 /></button></div></article>)}</section> : <section className="documents-empty"><span><FiFileText /></span><h2>{query ? 'No matching documents' : 'Bring in your first document'}</h2><p>{query ? 'Try a different search term.' : 'Upload a PDF, Word document, image, or text file to keep it in your workspace.'}</p>{!query && <button className="button button-dark" onClick={() => input.current?.click()}><FiUploadCloud /> Upload document</button>}</section>}{analysis && <div className="analysis-modal-wrap"><button className="analysis-backdrop" onClick={() => setAnalysis(null)} aria-label="Close analysis" /><section className="analysis-modal"><header><div><p className="eyebrow">AI DOCUMENT ANALYSIS</p><h2>{analysis.fileName}</h2></div><button onClick={() => setAnalysis(null)}><FiX /></button></header><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{analysis.analysis || 'No analysis was returned.'}</ReactMarkdown></div><p className="analysis-disclaimer">Use this as an aid to review, not as a substitute for advice from a qualified lawyer.</p></section></div>}</AppShell>;
}
