import { useEffect, useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { FiArrowRight, FiLock, FiMail, FiShield } from 'react-icons/fi';
import Logo from '../components/Logo';
import { useAuth } from '../context/AuthContext';
import { authService } from '../services/authService';
import { getErrorMessage } from '../services/api';

export default function Login() {
  const { completeAuthentication, isAuthenticated } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const googleButton = useRef(null);
  const [form, setForm] = useState({ email: '', password: '' }); const [twoFactor, setTwoFactor] = useState(false); const [otp, setOtp] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const destination = location.state?.from || '/dashboard';
  useEffect(() => { if (isAuthenticated) navigate('/dashboard', { replace: true }); }, [isAuthenticated, navigate]);
  const finish = (payload) => { completeAuthentication(payload); navigate(destination, { replace: true }); };
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const payload = await authService.login(form); if (payload.requiresTwoFactor) { setTwoFactor(true); return; } finish(payload); } catch (err) { setError(getErrorMessage(err, 'We could not sign you in.')); } finally { setLoading(false); } };
  const verify = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { finish(await authService.verifyTwoFactor({ email: form.email, otp })); } catch (err) { setError(getErrorMessage(err, 'The verification code could not be confirmed.')); } finally { setLoading(false); } };
  useEffect(() => {
    const clientId = import.meta.env.VITE_GOOGLE_CLIENT_ID; if (!clientId || !googleButton.current) return undefined;
    const script = document.createElement('script'); script.src = 'https://accounts.google.com/gsi/client'; script.async = true;
    script.onload = () => { window.google?.accounts.id.initialize({ client_id: clientId, callback: async ({ credential }) => { setLoading(true); setError(''); try { finish(await authService.googleLogin(credential)); } catch (err) { setError(getErrorMessage(err, 'Google sign-in could not be completed.')); } finally { setLoading(false); } } }); window.google?.accounts.id.renderButton(googleButton.current, { theme: 'outline', size: 'large', width: 340, text: 'continue_with' }); };
    document.head.appendChild(script); return () => script.remove();
  }, []);
  return <div className="auth-page"><section className="auth-aside"><Link to="/"><Logo light /></Link><div className="auth-aside-copy"><p className="eyebrow">PRIVATE LEGAL WORKSPACE</p><h1>Make room for better legal thinking.</h1><p>Access your conversations, documents, and account from one calm, secure place.</p></div><div className="auth-orb auth-orb-one" /><div className="auth-orb auth-orb-two" /><p className="auth-aside-foot"><FiShield /> Your information is handled through your authenticated account.</p></section><main className="auth-main"><div className="auth-card"><Link className="back-home" to="/">← Back to home</Link><p className="eyebrow">WELCOME BACK</p><h2>{twoFactor ? 'Confirm it’s you' : 'Sign in to Dastavez'}</h2><p className="auth-subtitle">{twoFactor ? `Enter the verification code sent to ${form.email}.` : 'Continue to your legal intelligence workspace.'}</p>{error && <p className="form-error">{error}</p>}{twoFactor ? <form onSubmit={verify} className="form-stack"><label>Verification code<input inputMode="numeric" autoComplete="one-time-code" value={otp} onChange={(event) => setOtp(event.target.value)} placeholder="6-digit code" required /></label><button className="button button-dark full-width" disabled={loading}>{loading ? 'Verifying…' : <>Verify and continue <FiArrowRight /></>}</button><button className="text-button" type="button" onClick={() => setTwoFactor(false)}>Use another account</button></form> : <form onSubmit={submit} className="form-stack"><label>Email address<span className="input-with-icon"><FiMail /><input type="email" autoComplete="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="you@example.com" required /></span></label><label>Password<span className="input-with-icon"><FiLock /><input type="password" autoComplete="current-password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Your password" required /></span></label><button className="button button-dark full-width" disabled={loading}>{loading ? 'Signing in…' : <>Sign in <FiArrowRight /></>}</button></form>}<div className="auth-divider"><span>or</span></div>{import.meta.env.VITE_GOOGLE_CLIENT_ID ? <div ref={googleButton} className="google-login" /> : null}<p className="auth-switch">New to Dastavez? <Link to="/register">Create an account</Link></p></div></main></div>;
}
