import { useEffect, useRef, useState } from 'react';
import { FiCamera, FiCheck, FiLock, FiMail, FiSave, FiShield } from 'react-icons/fi';
import AppShell from '../components/AppShell';
import LoadingSpinner from '../components/LoadingSpinner';
import { useAuth } from '../context/AuthContext';
import { authService } from '../services/authService';
import api, { getErrorMessage } from '../services/api';

export default function Profile() {
  const { user, updateUser } = useAuth(); const [profile, setProfile] = useState(user); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [imageLoading, setImageLoading] = useState(false); const [twoFactor, setTwoFactor] = useState(Boolean(user?.twoFactorEnabled)); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const fileInput = useRef(null);
  useEffect(() => { api.get('/profile/info').then((response) => { setProfile(response.data); updateUser(response.data); }).catch((err) => setError(getErrorMessage(err, 'We could not load your profile.'))).finally(() => setLoading(false)); }, [updateUser]);
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const response = await api.put('/profile/info', { firstName: profile.firstName, lastName: profile.lastName }); setProfile(response.data.user); updateUser(response.data.user); setNotice('Your profile details have been updated.'); } catch (err) { setError(getErrorMessage(err, 'Your profile could not be updated.')); } finally { setSaving(false); } };
  const toggleTwoFactor = async () => { setError(''); try { const response = await authService.toggleTwoFactor(); setTwoFactor(response.twoFactorEnabled); const next = { ...profile, twoFactorEnabled: response.twoFactorEnabled }; setProfile(next); updateUser(next); setNotice(response.twoFactorEnabled ? 'Two-step verification is now enabled.' : 'Two-step verification is now disabled.'); } catch (err) { setError(getErrorMessage(err, 'Two-step verification could not be updated.')); } };
  const uploadPhoto = async (file) => { if (!file) return; setImageLoading(true); setError(''); try { const form = new FormData(); form.append('profileImage', file); const response = await api.post('/profile/profile-image', form, { headers: { 'Content-Type': 'multipart/form-data' } }); const next = { ...profile, profileImage: response.data.imageUrl }; setProfile(next); updateUser(next); setNotice('Your profile photo has been updated.'); } catch (err) { setError(getErrorMessage(err, 'Your profile photo could not be updated.')); } finally { setImageLoading(false); } };
  const name = [profile?.firstName, profile?.lastName].filter(Boolean).join(' ') || 'Your account';
  return <AppShell eyebrow="ACCOUNT SETTINGS" title="Your profile">{loading ? <LoadingSpinner label="Loading your profile" /> : <div className="profile-layout">{notice && <p className="notice notice-success"><FiCheck /> {notice}</p>}{error && <p className="notice notice-error">{error}</p>}<section className="profile-identity"><div className="profile-avatar-large">{profile?.profileImage ? <img src={profile.profileImage} alt="Profile" /> : <span>{`${profile?.firstName?.[0] || ''}${profile?.lastName?.[0] || ''}` || 'U'}</span>}<button onClick={() => fileInput.current?.click()} disabled={imageLoading} title="Change profile photo"><FiCamera /></button><input ref={fileInput} type="file" accept="image/*" hidden onChange={(event) => uploadPhoto(event.target.files?.[0])} /></div><h2>{name}</h2><p>{profile?.email}</p><span className="profile-tier">{profile?.subscriptionStatus || profile?.userTier || 'Free'} plan</span></section><div className="profile-content"><form className="settings-card" onSubmit={save}><header><div><p className="eyebrow">PERSONAL DETAILS</p><h2>Account information</h2></div></header><div className="two-inputs"><label>First name<input value={profile?.firstName || ''} onChange={(event) => setProfile({ ...profile, firstName: event.target.value })} required minLength="2" /></label><label>Last name<input value={profile?.lastName || ''} onChange={(event) => setProfile({ ...profile, lastName: event.target.value })} required minLength="2" /></label></div><label>Email address<span className="input-with-icon"><FiMail /><input value={profile?.email || ''} disabled /></span></label><p className="field-note">To change your email address, use the verified email-change process provided by the API. It is intentionally not changed through the name form.</p><button className="button button-dark" disabled={saving}>{saving ? 'Saving…' : <><FiSave /> Save changes</>}</button></form><section className="settings-card security-card"><header><div><p className="eyebrow">SECURITY</p><h2>Protect your access</h2></div></header><div className="security-option"><span className="security-icon"><FiShield /></span><div><strong>Two-step verification</strong><p>Ask for an email verification code after your password when signing in.</p></div><button className={`toggle ${twoFactor ? 'on' : ''}`} onClick={toggleTwoFactor} role="switch" aria-checked={twoFactor}><span /></button></div><div className="security-option disabled-option"><span className="security-icon"><FiLock /></span><div><strong>Password changes</strong><p>Use the account recovery flow to request a password reset through your verified email.</p></div></div></section></div></div>}</AppShell>;
}
