import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { FiArrowLeft, FiArrowRight, FiCheckCircle, FiMail, FiShield } from 'react-icons/fi';
import Logo from '../components/Logo';
import { authService } from '../services/authService';
import { getErrorMessage } from '../services/api';
import { useAuth } from '../context/AuthContext';

export default function Register() {
  const navigate = useNavigate(); const { completeAuthentication } = useAuth(); const [step, setStep] = useState(1); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [form, setForm] = useState({ firstName: '', lastName: '', email: '', password: '', confirmPassword: '', otp: '' });
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const requestOtp = async (event) => { event.preventDefault(); setError(''); setMessage(''); setLoading(true); try { const result = await authService.checkEmail(form.email); if (result.exists) { setError('An account already exists for this email. Sign in instead.'); } else { setMessage('We sent a verification code to your email.'); setStep(2); } } catch (err) { setError(getErrorMessage(err, 'We could not send a verification code.')); } finally { setLoading(false); } };
  const create = async (event) => { event.preventDefault(); setError(''); if (form.password !== form.confirmPassword) { setError('The passwords do not match.'); return; } setLoading(true); try { const payload = await authService.signup(form); completeAuthentication(payload); navigate('/dashboard'); } catch (err) { setError(getErrorMessage(err, 'We could not create your account.')); } finally { setLoading(false); } };
  return <div className="auth-page"><section className="auth-aside"><Link to="/"><Logo light /></Link><div className="auth-aside-copy"><p className="eyebrow">START WITH CLARITY</p><h1>A better home for your legal work.</h1><p>Ask questions, understand documents, and keep each legal matter within reach.</p></div><div className="auth-orb auth-orb-one" /><div className="auth-orb auth-orb-two" /><p className="auth-aside-foot"><FiShield /> Legal information with the context and care it deserves.</p></section><main className="auth-main"><div className="auth-card"><Link className="back-home" to="/">← Back to home</Link><p className="eyebrow">CREATE YOUR ACCOUNT</p><h2>{step === 1 ? 'Start your workspace' : 'Verify your email'}</h2><p className="auth-subtitle">{step === 1 ? 'We’ll verify your email before creating your account.' : 'Enter the code we sent, then choose a secure password.'}</p><div className="register-steps"><span className={step >= 1 ? 'current' : ''}>1</span><i /><span className={step >= 2 ? 'current' : ''}>2</span></div>{error && <p className="form-error">{error}</p>}{message && <p className="form-success"><FiCheckCircle /> {message}</p>}{step === 1 ? <form className="form-stack" onSubmit={requestOtp}><label>Email address<span className="input-with-icon"><FiMail /><input type="email" name="email" autoComplete="email" value={form.email} onChange={update} placeholder="you@example.com" required /></span></label><button className="button button-dark full-width" disabled={loading}>{loading ? 'Sending code…' : <>Continue <FiArrowRight /></>}</button></form> : <form className="form-stack" onSubmit={create}><div className="two-inputs"><label>First name<input name="firstName" value={form.firstName} onChange={update} required minLength="2" /></label><label>Last name<input name="lastName" value={form.lastName} onChange={update} required minLength="2" /></label></div><label>Verification code<input name="otp" inputMode="numeric" autoComplete="one-time-code" value={form.otp} onChange={update} placeholder="6-digit code" required /></label><label>Password<input type="password" name="password" autoComplete="new-password" value={form.password} onChange={update} placeholder="At least 6 characters" minLength="6" required /></label><label>Confirm password<input type="password" name="confirmPassword" autoComplete="new-password" value={form.confirmPassword} onChange={update} placeholder="Repeat your password" minLength="6" required /></label><button className="button button-dark full-width" disabled={loading}>{loading ? 'Creating account…' : <>Create account <FiArrowRight /></>}</button><button type="button" className="text-button" onClick={() => setStep(1)}><FiArrowLeft /> Use another email</button></form>}<p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></div></main></div>;
}
