import { useEffect, useState } from 'react';
import { FiCheck, FiInfo, FiShield, FiX } from 'react-icons/fi';
import AppShell from '../components/AppShell';
import LoadingSpinner from '../components/LoadingSpinner';
import { subscriptionService } from '../services/subscriptionService';
import { getErrorMessage } from '../services/api';

const price = (amount) => amount === 0 ? 'Included' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount);
export default function Subscription() {
  const [state, setState] = useState({ loading: true, prices: [], features: [], subscription: null, error: '' }); const [notice, setNotice] = useState(''); const [canceling, setCanceling] = useState(false);
  useEffect(() => { let alive = true; Promise.allSettled([subscriptionService.prices(), subscriptionService.features(), subscriptionService.mine()]).then(([prices, features, mine]) => { if (!alive) return; setState({ loading: false, prices: prices.status === 'fulfilled' ? prices.value.prices || [] : [], features: features.status === 'fulfilled' ? Object.values(features.value.features || {}) : [], subscription: mine.status === 'fulfilled' ? mine.value.subscription : null, error: prices.status === 'rejected' && mine.status === 'rejected' ? 'We could not load subscription information.' : '' }); }); return () => { alive = false; }; }, []);
  const cancel = async () => { if (!window.confirm('Cancel your subscription at the end of the current billing period?')) return; setCanceling(true); try { const response = await subscriptionService.cancel(); setNotice(response.message); setState((current) => ({ ...current, subscription: { ...current.subscription, status: 'cancelled' } })); } catch (err) { setState((current) => ({ ...current, error: getErrorMessage(err, 'Your subscription could not be cancelled.') })); } finally { setCanceling(false); } };
  const currentTier = state.subscription?.tier || 'free';
  return <AppShell eyebrow="PLANS & ACCESS" title="A plan that fits your practice">{state.loading ? <LoadingSpinner label="Loading plan information" /> : <>{notice && <p className="notice notice-success">{notice}</p>}{state.error && <div className="notice notice-error"><span>{state.error}</span><button onClick={() => setState((current) => ({ ...current, error: '' }))}><FiX /></button></div>}<section className="subscription-summary"><div><p className="eyebrow">CURRENT ACCESS</p><h2>{currentTier} <span>plan</span></h2><p>{state.subscription?.status === 'active' ? 'Your subscription is active.' : 'You are currently using the available free access.'}</p></div>{currentTier !== 'free' && <button className="button button-outline" disabled={canceling} onClick={cancel}>{canceling ? 'Cancelling…' : 'Cancel subscription'}</button>}</section><section className="pricing-grid">{state.prices.map((tier) => { const isCurrent = currentTier === tier.tier; const tierFeatures = state.features.filter((feature) => feature.minTier === tier.tier).slice(0, 4); return <article key={tier.tier} className={`price-card ${isCurrent ? 'current' : ''} ${tier.tier === 'premium' ? 'featured' : ''}`}>{tier.tier === 'premium' && <span className="popular-badge">MOST COMPLETE</span>}<p className="price-tier">{tier.tier}</p><h2>{price(tier.amount)}</h2><p className="price-description">{tier.messageLimit === -1 ? 'No message limit configured' : `${tier.messageLimit} messages in the configured period`}</p><span className="price-rule" /><ul>{tierFeatures.length ? tierFeatures.map((feature) => <li key={feature.key}><FiCheck /> {feature.label}</li>) : <li><FiCheck /> Core workspace access</li>}</ul>{isCurrent ? <span className="current-plan"><FiCheck /> Current plan</span> : <button className="button button-muted" disabled>Payment setup required</button>}</article>; })}</section><section className="payment-note"><FiInfo /><div><h3>Payment integration status</h3><p>The active subscription API exposes plan information and account status. Its upgrade endpoint is explicitly marked by the backend for use only after a verified payment webhook is connected, so this screen does not activate paid access without payment confirmation.</p></div><FiShield /></section></>}</AppShell>;
}
